"""rename  user role name field

Revision ID: 747ca9c71f87
Revises: 53a5219700cb
Create Date: 2021-03-11 21:20:59.890212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '747ca9c71f87'
down_revision = '53a5219700cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('rolename', sa.String(length=50), nullable=True))
    op.drop_index('name', table_name='role')
    op.create_unique_constraint(None, 'role', ['rolename'])
    op.drop_column('role', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_index('name', 'role', ['name'], unique=True)
    op.drop_column('role', 'rolename')
    # ### end Alembic commands ###
