"""modify model SensorConfig2

Revision ID: 928e9e29f05c
Revises: 3e85c818a5a9
Create Date: 2021-02-26 14:42:15.023219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928e9e29f05c'
down_revision = '3e85c818a5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_config', sa.Column('highervalue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_config', 'highervalue')
    # ### end Alembic commands ###
